# TankEvents Plug-in
# Initial code generated by Softimage SDK Wizard
# Executed Tue Oct 9 15:16:46 EDT 2012 by bgabe
# 
# Tip: To add a command to this plug-in, right-click in the 
# script editor and choose Tools > Add Command.
import win32com.client
from win32com.client import constants
import os

null = None
false = 0
true = 1

def XSILoadPlugin( in_reg ):
    in_reg.Author = "bgabe"
    in_reg.Name = "TankEvents"
    in_reg.Major = 1
    in_reg.Minor = 0

    in_reg.RegisterEvent("tk_StartTankEngine",constants.siOnStartup)
    #RegistrationInsertionPoint - do not remove this line

    return true

def XSIUnloadPlugin( in_reg ):
    strPluginName = in_reg.Name
    Application.LogMessage(str(strPluginName) + str(" has been unloaded."),constants.siVerbose)
    return true

def tk_StartTankEngine_OnEvent( in_ctxt ):
    project_root = os.environ.get('TANK_SOFTIMAGE_PROJECT_ROOT', "")
    entity_type = os.environ.get('TANK_SOFTIMAGE_ENTITY_TYPE', "")
    entity_id = os.environ.get('TANK_SOFTIMAGE_ENTITY_ID', "")
    if not project_root:
        Application.LogMessage("Starting Softimage in Normal Mode", 8)
    else:
        Application.LogMessage("Starting Softimage in Pipeline Mode", 8)
        Application.LogMessage("Project_Root: "+project_root)
        Application.LogMessage("Entity_Type: "+entity_type)
        Application.LogMessage("Entity_ID: "+entity_id)

        started = Application.Tank_StartEngine()
        if started:
            Application.Tank_SetProjectFromContext()

    